# -*- coding: utf-8 -*-
"""pharmacy_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-fw4ljLyTCQG90ZpS3usL5a_DmXk-GaQ
"""

import pandas as pd

# Load the dataset from CSV file
file_path = '/medicine_data.csv'  # Use the correct file path
df = pd.read_csv(file_path)

# Filter only available medicines
available_medicines = df[df["Availability"] == "In Stock"]

# Simplified function to calculate distance (you should replace this with actual distance calculation)
def calculate_distance(location):
    return len(location)

# Assume hospital location (this is a simplified approach)
hospital_location = "123 Hospital St"

# Calculate distances for available medicines and sort by distance
available_medicines["Distance"] = available_medicines["Location"].apply(calculate_distance)
available_medicines = available_medicines.sort_values(by="Distance")

# Group available medicines by MedicineName and list pharmacies
medicine_pharmacy_mapping = available_medicines.groupby("MedicineName")["PharmacyName"].apply(list)

# Print the results
for medicine, pharmacies in medicine_pharmacy_mapping.items():
    print(f"Medicine: {medicine}")
    print("Available at pharmacies (nearest to farthest):")
    for pharmacy in pharmacies:
        print(f"- {pharmacy}")
    print("=" * 40)